name: motion_snackbar
description: "Flutter package for animated snackbars. Includes success, error, info, warning, & custom styles with smooth directional animations. Customize message, description, color & duration for improved feedback."
version: 0.0.3
homepage: https://github.com/deadlium
repository: https://github.com/deadlium/animated_snackbars

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
